### ISSUE TITLE
Target peds?

### ISSUE THREAD

**Issue by FjamZoo** [BerkieBb/bt-target#1]
Is there a posibility to utilize the target specific peds? So I can have a more simple solution to hunting triggers and so on?

**Comment by BerkieBb** [comment]
@FjamZoo Yes, you can use the AddTargetModel in an export or use the Config table called Config.TargetModels

**Comment by FjamZoo** [comment]
> @FjamZoo Yes, you can use the AddTargetModel in an export or use the Config table called Config.TargetModels

Alright I appreciate it, one change that I would love to see is a possibility for AddTargetModel is specific cars. This Is how I had it setup on the last update

-- Possibility to target specific vehicles


for _, option in pairs(Bones[_]["options"]) do
    if option.shouldShow == nil or option.shouldShow() then
        if GetEntityModel(nearestVehicle) == option.vehicle or option.vehicle == nil then
            for job, grade in pairs(option.job) do
                if grade == "all" or (Config.UseGrades and (job == PlayerJob.name and (Config.QBCore and grade == PlayerJob.grade.level) or (Config.ESX and grade == PlayerJob.grade))) or grade == PlayerJob.name then
                    option2 = ShallowCopy(option)
                    option2.shouldShow = nil
                    table.insert(NewOptions, option2)
                end
            end
        end
    end
end

local bones = {
    "door_dside_r",
    "door_pside_r"
}
exports['bt-target']:AddTargetBone(bones, {
options = {
    {
    event = "qb-truckrobbery:client:eye:unlock",
    icon = "fas fa-door-open",
    label = "Unlock Door",
    job = {"all"},
    vehicle = GetHashKey("stockade"),
    },
},
distance = 1.5
})

**Comment by BerkieBb** [comment]
The only thing you need to change to make it work is remove the job or set it to false
