### ISSUE TITLE
Hello, thanks for the great effort

### ISSUE THREAD

**Issue by darknight2590** [BerkieBb/bt-target#13]
Hello, thanks for the great effort
I think the script is theoretically the best out there
but export It has many problems
Use config In entering the information
something new
The problems started when programmers switched from the normal system to your system
See the amount of problems when using
Not everyone can convert to your script
I wish I could reproduce and rewrite the code
For compatibility with all versions
To make it easier for people to move to your script

**Comment by darknight2590** [comment]
I think it is better to review the project
And provide an update that solves all the problems
With the addition of examples on the use of each example
The project is very powerful in theory
When applying, there is great difficulty
and export problems

**Comment by BerkieBb** [comment]
That's the thing, I tried my best on keeping it user friendly but I can't if I want to keep it optimized

**Comment by darknight2590** [comment]
The problem is with adding to config.lua
I would like to delete this suggestion
And keep the use through export

**Comment by darknight2590** [comment]
The biggest problem
For example we use
Previous versions of bt-target
And when using your project
Add codes that work on previous versions
Adding features to your project does not work

**Comment by BerkieBb** [comment]
I won't delete the config, I'll just add a much better detailed wiki to it

**Comment by BerkieBb** [comment]
And I still have to fix stuff
