### ISSUE TITLE
Could you provide an example in the cofig.lua

### ISSUE THREAD

**Issue by Archangelza1** [BerkieBb/bt-target#2]
First off love the resource however since I migrated from the brent one to you one none of it is working i know its probably an option that im not inputting so thought it would be handy to put an example in the config :)

**Comment by BerkieBb** [comment]
@Archangelza1 That's all coming, I cleaned the whole repo because if the v2 and I'm working on a wiki and readme and making examples, but I'm on vacation so I have less time and I can't test my changes unfortunately so I have to rely on others

**Comment by Archangelza1** [comment]
No problem at all could i ask for a basic boxzone example for now and im sure ill figure out the rest :) also do you have plans reworking the UI :)

**Comment by Archangelza1** [comment]
Ill be happy to beta test for you aswell if you would like :)

**Comment by BerkieBb** [comment]
@Archangelza1 I wanted to rework the ui sometime but I just don't know how, if you have any tips, be sure to tell me and I'll be putting all my beta stuff on the testing branch.

Here is a basic boxzone

```lua
    ["MechanicDuty"] = {
       name = "MechanicDuty",
       coords = vector3(-206.16, -1341.66, 34.89),
       length = 1.3,
       width = 0.3,
       heading = 0,
       debugPoly = true,
       minZ = 33.89,
       maxZ = 36.18,
         options = {
            {
                type = "client", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
                event = "string",
                parameters = {}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
                icon = "fas fa-circle", -- an example one, get it from fontawesome.com
                label = "string",
                job = "string" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
            },
        },
        distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
    },
```

**Comment by Archangelza1** [comment]
Sure thing, do you have discord and maybe i can discuss it basically what im thinking is a dot that transforms to the Font Awesome Icon for the action and possible a radial kinda menu for multiple interaction :) , and i appreciate it alot

**Comment by BerkieBb** [comment]
You can join the qbcore framework discord, I give support there in the bt-target channel.
https://discord.gg/qbcore
