### ISSUE TITLE
unable to use box?

### ISSUE THREAD

**Issue by mrdeano** [BerkieBb/bt-target#3]
hey so i was testing this out and i see you posted your example in another issue but when i go in game and try it i press alt to bring up the eye and nothing shows here is my config

local Config, Entities, Models, Zones, Bones, Players, Types, Intervals, ConfigFunctions, PlayerData = {}, {}, {}, {}, {}, {}, {}, {}, {}, {}
Types[1], Types[2], Types[3] = {}, {}, {}

Config.ESX = true
Config.QBCore = false
Config.UseGrades = false
Config.LindenInventory = false
Config.MaxDistance = 2 -- Fallback for if you left the distance in the wrong place or forgot it
Config.Debug = false -- Debug mode

Config.VehicleBones = {'chassis', 'windscreen', 'seat_pside_r', 'seat_dside_r', 'bodyshell', 'suspension_lm', 'suspension_lr', 'platelight', 'attach_female', 'attach_male', 'bonnet', 'boot', 'chassis_dummy', 'chassis_Control', 'door_dside_f', 'door_dside_r', 'door_pside_f', 'door_pside_r', 'Gun_GripR', 'windscreen_f', 'platelight', 'VFX_Emitter', 'window_lf', 'window_lr', 'window_rf', 'window_rr', 'engine', 'gun_ammo', 'ROPE_ATTATCH', 'wheel_lf', 'wheel_lr', 'wheel_rf', 'wheel_rr', 'exhaust', 'overheat', 'misc_e', 'seat_dside_f', 'seat_pside_f', 'Gun_Nuzzle', 'seat_r'}

Config.BoxZones = {
   -- the name of the table and the name parameter can be the same
   ["OpenCloakroomMenu"] = { -- has to be unique
   name = "OpenCloakroomMenu", -- has to be unique
   coords = vector3(461.22,-1000.01,31.689), -- example coords
   length = 1.0, -- float value
   width = 4.0, -- float value
   heading = 178.0, -- integer
   debugPoly = true, -- boolean, it makes a green box if true
   minZ = 30.00, -- float value
   maxZ = 31.30, -- float value
	 options = {
		{
			type = "function", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
			event = "esx_policejob:OpenCloakroomMenu",
			-- parameters = {}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
			icon = "fas fa-shield-alt", -- an example one, get it from fontawesome.com
			label = "Change Clothes",
			job = "police" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
		},
	},
	distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
},
}

Config.CircleZones = {

}

Config.TargetModels = {

}

Config.TargetEntities = {

}

Config.TargetBones = {

}

Config.EntityZones = {
    
}

Config.PedOptions = {

}

Config.VehicleOptions = {

}

Config.ObjectOptions = {

}

Config.PlayerOptions = {

}

ConfigFunctions.ItemCount = function(item)
	if Config.LindenInventory then return exports['linden_inventory']:CountItems(item)[item] > 0
    elseif Config.ESX then
		for k, v in pairs(PlayerData.inventory) do
			if v.name == item then
				return v.count > 0
			end
		end
    elseif Config.QBCore then
        for k, v in pairs(PlayerData.items) do
			if v.name == item then
				return v.amount > 0
			end
		end
	end

	return false
end

return Config, Entities, Models, Zones, Bones, Players, Types, Intervals, ConfigFunctions, PlayerData

**Comment by Ventraks** [comment]
Same here.

**Comment by BerkieBb** [comment]
You put the type to function which triggers a function inside bt-target but in the evenr you put a client event so the type has to be client

**Comment by BerkieBb** [comment]
But you also need to read the readme I recently made to understand why it doesn't work if it doesn't after the help I gave you

**Comment by mrdeano** [comment]
> But you also need to read the readme I recently made to understand why it doesn't work if it doesn't after the help I gave you

i try to read the readme but nothing has changed in it 0.0

here is a gif i made showing that i can not see it

https://gyazo.com/b5c239ffeeb03e803245292949c76b22

**Comment by BerkieBb** [comment]
In the readme I wrote that this is a work in progress and it may not work properly, but you have a really big zone, you need to know that the target reacts to the center of the zone and that center is unreachable with your zone

**Comment by mrdeano** [comment]
oh ok i made it smaller still can not use it :/

**Comment by BerkieBb** [comment]
Test the box on an empty area, if that doesn't work, then polyzones don't work yet unfortunately

**Comment by mrdeano** [comment]
yeah that's that i did i made it float in the air and ya dont work :/

**Comment by Ventraks** [comment]
Config.BoxZones = {
	--burgershot
    ["Sign"] = {
        name = "Sign",
        coords = vector3(-1196.87, -902.86, 13.99),
        length = 0.4,
        width = 1.1,
        heading = 212.0,
        debugPoly = true,
        minZ = 13.69,
        maxZ = 15.06,
        options = {
            {
                event = "qb-burgershotjob:burgershot:DutyB",
                icon = "far fa-clipboard",
                label = "Sign",
                job = {"all"},
            },
        },
        distance = 3
    },
 }
 

I have this and small zone but still doesnt work

**Comment by Ventraks** [comment]
![image](https://user-images.githubusercontent.com/83806248/127234456-4c380cb5-36bf-4166-b38b-bcbe769b39fc.png)

**Comment by BerkieBb** [comment]
Then the polyzones don't work yet, I am home in a week so I'll fix lots and add lots then

**Comment by BerkieBb** [comment]
> Config.BoxZones = {
> --burgershot
> ["Sign"] = {
> name = "Sign",
> coords = vector3(-1196.87, -902.86, 13.99),
> length = 0.4,
> width = 1.1,
> heading = 212.0,
> debugPoly = true,
> minZ = 13.69,
> maxZ = 15.06,
> options = {
> {
> event = "qb-burgershotjob:burgershot:DutyB",
> icon = "far fa-clipboard",
> label = "Sign",
> job = {"all"},
> },
> },
> distance = 3
> },
> }
> 
> I have this and small zone but still doesnt work

Change job = {"all"} to job = false

**Comment by BerkieBb** [comment]
@Ventraks did yours work or does it still not work?

**Comment by Ventraks** [comment]
> @Ventraks did yours work or does it still not work?

Nothing changed.

**Comment by BerkieBb** [comment]
Can you guys check if it works after the updates I did yesterday?

**Comment by Ventraks** [comment]
![Snímek obrazovky 2021-07-29 114154](https://user-images.githubusercontent.com/83806248/127469920-84137e73-519c-4b7c-92a7-2cbda660836a.png)

I downloaded newest version

**Comment by BerkieBb** [comment]
@Ventraks fixed it

**Comment by Ventraks** [comment]
idk bro :// nothing changes and small polyzones are bullshit

**Comment by BerkieBb** [comment]
Yeah sorry then, I can't do anything about it unless someone else tests and debugs for me so I know where the problem lies, otherwise you'll have to wait a week for me to get off my vacation and fix it afterwards

**Comment by Ventraks** [comment]
Config.TargetModels = {
	["shops"] = {
        models = {
            `cs_josef`,
            `mp_m_shopkeep_01`,
            `mp_m_waremech_01`,
            `a_m_y_smartcaspat_01`
        },
        options = {
            {
                type = "client",
                event = "qb-shops:marketshop",
                parameters = {},
                icon = "fas fa-shopping-basket",
                label = "OPEN SHOP",
                job = false
            },
        },
        distance = 2.5
    },
}

Something wrong on this code?

**Comment by BerkieBb** [comment]
I think you're missing one closint bracket at the end, everything else is good

**Comment by Ventraks** [comment]
I'll wait until you repair it

**Comment by BerkieBb** [comment]
@Ventraks I may have found the problem, if you could check now if it works?
