### ISSUE TITLE
No such export

### ISSUE THREAD

**Issue by vsyyyy** [BerkieBb/bt-target#46]
![export](https://user-images.githubusercontent.com/70838371/136834524-f72de83b-f9d4-4830-a303-d2aaefc8f2f1.png)

**Comment by BerkieBb** [comment]
Do you have qb-core installed?
Do you have the latest version of qb-core?
Is qb-core started before qb-target is?

**Comment by BerkieBb** [comment]
Replace your current getobject method just with
`local QBCore = exports['qb-core']:GetCoreObject`
This can be done for server and client side, the local can be removed if needed
