### ISSUE TITLE
attempt to call a nil value?

### ISSUE THREAD

**Issue by vsyyyy** [BerkieBb/bt-target#48]
I just downloaded qb-target just after installing the new qb-core and oxmysql- I start it and get this error?

![image](https://user-images.githubusercontent.com/70838371/137339153-e3733d31-5b04-4553-b06f-c525f6e6ebab.png)

**Comment by BerkieBb** [comment]
Can you put that config in a codeblock so it keeps the spaces aligned, then I can identify your problem much easier
