### ISSUE TITLE
Missing = nill 

### ISSUE THREAD

**Issue by drkcmmndr-00** [BerkieBb/bt-target#5]
Getting parsing error at client/main.lua:75 after elseif  I assume that value is supposed to be            Types[type][labels] = nil in line 74?

**Comment by BerkieBb** [comment]
No I made sure that was right, the function is probably triggered with an invalid value

**Comment by BerkieBb** [comment]
Nope I looked wrong, you're totally right

**Comment by BerkieBb** [comment]
Fixed it, thanks for reporting the issue!
