### ISSUE TITLE
shouldShow = function()

### ISSUE THREAD

**Issue by darknight2590** [BerkieBb/bt-target#8]
I'm looking for the right use
shouldShow = function()

for example
When using the following traditional code

```
                for k, v in pairs(Config.Locations["duty"]) do
                    local dist = #(pos - vector3(v.x, v.y, v.z))
                    if dist < 5 then
                        if dist < 1.5 then
                            if onDuty then
                                DrawText3D(v.x, v.y, v.z, "~r~E~w~ - Go Off Duty")
                            else
                                DrawText3D(v.x, v.y, v.z, "~g~E~w~ - Go On Duty")
                            end
                            if IsControlJustReleased(0, 38) then
                                onDuty = not onDuty
                                TriggerServerEvent("QBCore:ToggleDuty")
                                TriggerServerEvent("police:server:UpdateBlips")
                            end
                        elseif dist < 4.5 then
                            DrawText3D(v.x, v.y, v.z, "on/off duty")
                        end  
                    end
                end
```
If you are logged in
It is when you approach DrawText3D
show Go Off Duty
and If you are out of work, he will give you
Go On Duty

Can this thing be applied through bt-target
Does it show the opposite? with shouldShow ?

**Comment by BerkieBb** [comment]
The shouldShow function is mostly intended for use with exports so you can get the variables from the resource and then for example the onDuty trigger in policejob will have a value and you can get onDuty and off-Duty with a single target label

**Comment by BerkieBb** [comment]
Just use it like this

```lua
shouldShow = function(entity)

end,
```
The entity is the entity you're looking at, you can use that too

**Comment by vanillla1** [comment]
The problem is that I implemented the idea
But I did not succeed in the application process
Do you have a live example?

**Comment by BerkieBb** [comment]
Make sure to put the shouldShow inside the options not outside
