### ISSUE TITLE
can i have a example?

### ISSUE THREAD

**Issue by mrdeano** [BerkieBb/bt-target#9]
can i have a example? for boxzone?

**Comment by Archangelza1** [comment]
Here is the exmaple :)

`   -- the name of the table and the name parameter can be the same
    ["string"] = { -- has to be unique
       name = "string", -- has to be unique
       coords = vector3(-206.16, -1341.66, 34.89), -- example coords
       length = 1.3, -- float value
       width = 0.3, -- float value
       heading = 0, -- integer
       debugPoly = true, -- boolean, it makes a green box if true
       minZ = 33.89, -- float value
       maxZ = 36.18, -- float value
         options = {
            {
                type = "client", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
                event = "string",
                parameters = {}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
                icon = "fas fa-circle", -- an example one, get it from fontawesome.com
                label = "string",
                job = "string" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
            },
        },
        distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
    },`

**Comment by Archangelza1** [comment]
Here is a box zonee example :)

```lua
-- the name of the table and the name parameter can be the same
    ["string"] = { -- has to be unique
       name = "string", -- has to be unique
       coords = vector3(-206.16, -1341.66, 34.89), -- example coords
       length = 1.3, -- float value
       width = 0.3, -- float value
       heading = 0, -- integer
       debugPoly = true, -- boolean, it makes a green box if true
       minZ = 33.89, -- float value
       maxZ = 36.18, -- float value
         options = {
            {
                type = "client", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
                event = "string",
                parameters = {}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
                icon = "fas fa-circle", -- an example one, get it from fontawesome.com
                label = "string",
                job = "string" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
            },
        },
        distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
    },```

**Comment by mrdeano** [comment]
> Here is a box zonee example :)
> 
> ```lua
> -- the name of the table and the name parameter can be the same
>     ["string"] = { -- has to be unique
>        name = "string", -- has to be unique
>        coords = vector3(-206.16, -1341.66, 34.89), -- example coords
>        length = 1.3, -- float value
>        width = 0.3, -- float value
>        heading = 0, -- integer
>        debugPoly = true, -- boolean, it makes a green box if true
>        minZ = 33.89, -- float value
>        maxZ = 36.18, -- float value
>          options = {
>             {
>                 type = "client", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
>                 event = "string",
>                 parameters = {}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
>                 icon = "fas fa-circle", -- an example one, get it from fontawesome.com
>                 label = "string",
>                 job = "string" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
>             },
>         },
>         distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
>     },
> ```

Thanks
will test to see if it works :D

**Comment by mrdeano** [comment]
@Archangelza1 can you please explan the parameters ?? please 

in my code i need to pass 2 verables v.job and v.grade

**Comment by Archangelza1** [comment]
could you explain what you mean you need to pass 2 variables ?

**Comment by mrdeano** [comment]
so my current event is openmenu(v.job, v.grade)

how would i use this?

**Comment by BerkieBb** [comment]
instead of `v.job, v.grade` make it `QBCore.Functions.GetPlayerData().job.name, QBCore.Functions.GetPlayerData().job.grade.level`

**Comment by mrdeano** [comment]
> instead of `v.job, v.grade` make it `QBCore.Functions.GetPlayerData().job.name, QBCore.Functions.GetPlayerData().job.grade.level`

so would it loo like this?

    ["string"] = { -- has to be unique
       name = "string", -- has to be unique
       coords = vector3(-206.16, -1341.66, 34.89), -- example coords
       length = 1.3, -- float value
       width = 0.3, -- float value
       heading = 0, -- integer
       debugPoly = true, -- boolean, it makes a green box if true
       minZ = 33.89, -- float value
       maxZ = 36.18, -- float value
         options = {
            {
                type = "client", -- client, server, function (only function in bt-target), action (if you use this you can make the action parameter a function, this will get the entity you're looking at sent to so you can check on that)
                event = "string",
                parameters = {ESX.GetPlayerData().job.name, ESX.GetPlayerData().job.grade.level}, -- put anything you want inside this to get it through an event get it with: data.parameters, same goes for any other option here, you can get them too
                icon = "fas fa-circle", -- an example one, get it from fontawesome.com
                label = "string",
                job = "string" -- or a table if you have more jobs, like this {["police"] = 1, ["ambulance"] = 3}
            },
        },
        distance = 2.0 -- float value in gta units, 1.8 is mostly against an object
    },


and in the event function that im trying to use what would i put here to get the prams? function(WHAT WOULD I PUT HERE?)

**Comment by BerkieBb** [comment]
1. You can't trigger a function outside of bt-target, only an event and now also a command.
2. That's not what I told you and it's grade not grade.level for ESX, you don't have to send parameters, just get the job and grade inside the function

**Comment by mrdeano** [comment]
sorry i must of miss put what i was trying to say

so this is the event im trying to use with this bt-target

```RegisterNetEvent("core_jobutilities:openBossMenu")
AddEventHandler("core_jobutilities:openBossMenu",function(j, l)
    ESX.TriggerServerCallback("core_jobutilities:getBossMenuData",function(grades, employees, fund, gradename)
            if Config.BossMenuUsers[gradename] ~= nil and job == j then
                SetNuiFocus(true, true)
                SendNUIMessage(
                    {
                        type = "openBoss",
                        job = {job = job, grade = grade},
                        employees = employees,
                        grades = grades,
                        fund = fund,
                        bossJob = j,
                        bossLabel = l,
                        perms = Config.BossMenuUsers[gradename]
                    }
                )
            else
                SendTextMessage(Config.Text["cant_access_bossmenu"])
            end
        end,j)
end)```

so ```j``` would be job and ```l``` would be lable of the job

so would i need to use this bt-target by calling there job?

or how could i do it?

Thanks
